[Variables]

; ---------------------------------------- Launcher

scale=1
spacing=10

;           Item 1 (Firefox)
e1X=1
e1Y=1
e1Image=#@#icons\firefox_line.png
e1Action=["C:\Program Files\Mozilla Firefox\firefox.exe"]

;           Item 2 (VLC)
e2X=2
e2Y=1
e2Image=#@#icons\vlc_line.png
e2Action=["C:\Program Files\VideoLAN\VLC\vlc.exe"]

;           Item 3 (Steam)
e3X=1
e3Y=2
e3Image=#@#icons\steam_line.png
e3Action=["C:\Program Files (x86)\Steam\steam.exe"]

;           Item 4 (Discord)
e4X=2
e4Y=2
e4Image=#@#icons\discord_line.png
e4Action=["C:\Users\tomen\AppData\Local\Discord\Update.exe" --processStart Discord.exe]

;           Item 5 (Blender)
e5X=1
e5Y=3
e5Image=#@#icons\blender_line.png
e5Action=["C:\Program Files\Blender Foundation\Blender 2.93\blender.exe"]

;           Item 6 (Pinterest)
e6X=2
e6Y=3
e6Image=#@#icons\pinterest_line.png
e6Action=["shell:Appsfolder\1424566A.147190DF3DE79_5byw4zywtsh80!App"]


; ---------------------------------------- Panel

pLX=#e6X#
pLY=#e6Y#
pImageTint=60,60,60,200

nText="Other"

sideOpen=0
sidePanel=1