[Variables]

; ---------------------------------------- Launcher

scale=1
spacing=10

;           Item 1
e1X=1.0
e1Y=1.0
e1Image="C:/Users/tomen/Pictures/ResourcesExtract/windows11/imageres_10.ico"
e1Action=["C:/Users/tomen/Desktop"]

;           Item 2
e2X=2.0
e2Y=1.0
e2Image="C:/Users/tomen/Pictures/darkGreen18x18.png"
e2Action=["C:/Users/tomen/Documents/Programme/VNC Viewer.exe"]

pLX=2.0
pLY=1.0
pImageTint=60,60,60,200

nText=Test

sideOpen=0
sidePanel=1