[Variables]

; ---------------------------------------- Launcher

scale=1
spacing=10

;           Item 1 (Access)
e1X=1.5
e1Y=1
e1Image=#@#icons\access_line.png
e1Action=["C:\Program Files\Microsoft Office\root\Office16\MSACCESS.EXE"]

;           Item 2 (Excel)
e2X=2.5
e2Y=1
e2Image=#@#icons\excel_line.png
e2Action=["C:\Program Files\Microsoft Office\root\Office16\EXCEL.EXE"]

;           Item 3 (PowerPoint)
e3X=1
e3Y=2
e3Image=#@#icons\powerpoint_line.png
e3Action=["C:\Program Files\Microsoft Office\root\Office16\POWERPNT.EXE"]

;           Item 4 (Publisher)
e4X=2
e4Y=2
e4Image=#@#icons\publisher_line.png
e4Action=["C:\Program Files\Microsoft Office\root\Office16\MSPUB.EXE"]

;           Item 5 (Word)
e5X=3
e5Y=2
e5Image=#@#icons\word_line.png
e5Action=["C:\Program Files\Microsoft Office\root\Office16\WINWORD.EXE"]


; ---------------------------------------- Panel

pLX=#e5X#
pLY=#e5Y#
pImageTint=60,60,60,200

nText="Office"

sideOpen=0
sidePanel=1