[Variables]

; ---------------------------------------- Launcher

scale=1
spacing=10

;           Item 1
e1X=2.0
e1Y=2.0
e1Image="C:/Users/tomen/Pictures/darkGreen18x18.png"
e1Action=["C:/Users/tomen/Pictures"]

;           Item 2
e2X=1.0
e2Y=1.0
e2Image="C:/Users/tomen/Pictures/BlueSkyNew18x18.png"
e2Action=["C:/Users/tomen/Pictures"]

pLX=2.0
pLY=2.0
pImageTint=60,60,60,200

nText=B

sideOpen=0
sidePanel=1