[Variables]

; ---------------------------------------- Launcher

scale=1
spacing=10

;           Item 1 (Minecraft)
e1X=2.5
e1Y=1
e1Image=#@#icons\minecraft_line.png
e1Action=["C:\Program Files (x86)\Minecraft Launcher\MinecraftLauncher.exe"]

;           Item 2 (MultiMC)
e2X=3
e2Y=2
e2Image=#@#icons\multiMC_line.png
e2Action=["C:\Program Files (x86)\MultiMC\MultiMC.exe"]

;           Item 3 (Nox)
e3X=2.5
e3Y=3
e3Image=#@#icons\nox_line.png
e3Action=["C:\Program Files (x86)\Nox\bin\Nox.exe"]

;           Item 4 (BlueStacks)
e4X=1.5
e4Y=3
e4Image=#@#icons\bluestacks_line.png
e4Action=["C:\Program Files\BlueStacks\Bluestacks.exe"]

;           Item 5 (Terraria Mod Loader)
e5X=1
e5Y=2
e5Image=#@#icons\tModLoader_line.png
e5Action=["C:\Program Files (x86)\Steam\steam.exe" -applaunch 1281930]

;           Item 6 (Terraria)
e6X=1.5
e6Y=1
e6Image=#@#icons\terraria_line.png
e6Action=["C:\Program Files (x86)\Steam\steam.exe" -applaunch 105600]

;           Item 6 (Mindustry)
e7X=2
e7Y=2
e7Image=#@#icons\mindustry_line.png
e7Action=["C:\Program Files (x86)\Steam\steam.exe" -applaunch 1127400]

; ---------------------------------------- Panel

pLX=#e2X#
pLY=#e3Y#
pImageTint=60,60,60,200

nText="Games"

sideOpen=1
sidePanel=0